sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "0.10"
    - node_js: "0.12"
env:
  matrix:
    - secure: n31j1/l4DcZycnZhdkESU/9kO8xI/jSQgFn4xxt0Aq6d2h8SOnqd8/8ac+2MyTuIEYDv/K0popPkMVOexQkyosQkyLpz1BIhBBwQ59XvMNmuvg5g22VqLO4FTgkG+udVzyK9AgyAomJt6H3Jj/nnpxf8WQQN3zbuAEuYNG14e7S7e1JV2TAXE72pUsVTfphxvrj/wKtBHYmh3Xl0CS5wjwSjbZ8E5F3HQ95ZEUNXQ7kS0WU4z+THxTk4TGehvMqVi8qHdBUXRee9CgthM/yxo2ojPdE78Kd76I8CWXl40QjglehFl8QNKVgCKMfc9sSKy5tBPmhAn/UvkcuP0+OoV9PSiw0i4fMHKId/u1lu8O8/wCz+ZpaSb5OlXxJ2SWj5fAY1EGOU4T3MB1MbvUL4eHYYCotbxHGTffSPbHjQ0Hs1+gCmjwYKOkSLczMExN5JPfU1rl3L7byjttlNe6f9LWcwh8rd55KlRRO6DfxuVaveZEjHA3jRB6MFQ+FnOi3EEi/FlopHkhBcD7Ul/iw+0IS0hA1S1/YDfe/8MDe3Xn30rEtapyLj0nVtgM+lce9N3NmUlSKA07Dbf5vF1K/z7VGp/3EjKEeskqzSiWF3c5Cu7rgt9V9TZFMrnPeyB5VpS4YfsT5z7QNxAapi7ZMzcKMmIQ9PwbsVhoex4CPvtIY=
    - secure: C2fhhYlJ3U4nw+Sd2tYeXSZSXsptQUEq6TyFc8WtKk/vD17KhZ7mBZn/al69zfYwKwvCu/eCLweveFrz5b6WDyFp5TXGZ72zZ9zRhHz1S4QLMjp3Lnm9GISY9KWFsfNsLX4Wn/bHz71cG/G2czX1NLeXNmG8IdlPVcMEtVOLigPLrVAUIFRIrwbViPGHAjsdTLolt7ahuI5XG7vAQbLuqbG7SUyySY10VqxbJi2JxY22S9YQIGJqgJ6JYtlv29mcYAZxl6u8cOrTPBeitAu5lOrQwiAfekF4Z3koKd+9y0LKtBnwjZOG3HpH2TrYTaVaugjofrVQN+ef2HmT7LokjipBihux7tXmFVIs1xyWqCfis5MaE8s4/6UFlLOnUx+mWyhRcwp/z+669K9eruMed9Fa3KdUrmDIMT6i3ew/iUs2wyfF8Jqu0Jji1VG2VOCUo8H/X+khHsFa8jdNXV2itSw9IRcUFfIoH8ENoSQLoVD55oyrRsDWsffiuVEYeg+c4Q9p9fVMMGF30YNe24K87TuUbuDjLhjbtIGCj+9u7NxyocKijTXTWjksQj87wxqRCNMLu9l/EILmuAi4LaEMlU7hXo9+HAS6lcKfZk1YcaGt4wfpElaeHheJk8pLQB3oEXdNntFgKbjIrqUZBV99+SPjxx9tBoQ1idp0qLTLnCY=
