sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "0.10"
    - node_js: "0.12"
env:
  secure: "TEPu4ZlMLlCBgNorHv/GSnJ6nZbpNbDusRsaxWOkprNzqnxXyd5f8TIYJ61C+LP1hIYi+PcFtkiL2nDzZuZynBOJ0Ozmq6jYTk/Jbaeo6n48Rbyhb2FsJY72625zIINJItgzKtDe2fDOfUPfIVpNnGvEImkzYO9PpC2tSQt5vwPi2Wl1y1bCo8mONBHSX5s4E48v26JruRBgGVoG9X1UTKfM3SC9I2Z5hr0saHl/a/iZelLdJcTB3+qI0IixVfznNVz0WCHMEIqTy+o6uyHxXQxto8JEcqd5qworatrejcLUJpsf+c+GcqUIql4ljIKIWpuDMYcrNiVOgQNiChNXjlobE+0LY2e98dczfTGpqjO6zsNuZOWzX4WGKca3BAMEYVxqMhi642eMq2f1ljgCMd4XLwXzIDKjPOZ3KKwnzbkqcR+tLikZE59sGy04nHMM86giN0CLAjlEBUbYbB72p77wSA6aSq/aJW4oqE0G7+YmBEKOk9dGcb1GZwTFbdnNk+5qQVwGVYJDUXM7hu/jrINg9jnuD0+e6Vn7WhefP8IM+pfHD6VwyYCCPRBHj2mKojWwHOFqzhZvwLlYZn+lKzFcZFMcPzs6tLmHQb7U22MreSUyz4f3KItwTuGmgg3Ilk16B7kJ4b2GcSWLpyWxO1QjMIXmc6oytoNWIm6zZzs="
